#@ load("@ytt:data", "data")

---
apiVersion: sql.tanzu.vmware.com/v1
kind: Postgres
metadata:
  name: #@ data.values.instance_name
spec:
 #!
 #! Global features
 #!
  pgConfig:
    dbname: postgres-sample
    username: pgadmin
    appUser: pgappuser
    #! additionalDatabases:
    #!   - dbName: twitter-emergency
    #!     appUser: pgappuser
  postgresVersion:
    name: postgres-14
  serviceType: #@ data.values.service_type
 #! serviceAnnotations:
  seccompProfile:
    type: RuntimeDefault
  imagePullSecret:
    name: regsecret
  #@ if data.values.high_availability > 0:
  highAvailability:
    enabled: true
  #@ end
  #@ if data.values.log_level != "":
  logLevel: #@ data.values.log_level
  #@ end
  #@ if data.values.backup_location != "":
  backupLocation:
     name: #@ data.values.backup_location
  #@ end
  #@ if data.values.certificate_secret_name != "":
  certificateSecretName: #@ data.values.certificate_secret_name
  #@ end

 #!
 #! Data Pod features
 #!
  storageClassName: #@ data.values.storage_class_name
  storageSize: #@ data.values.storage_size
  dataPodConfig:
#!    tolerations:
#!      - key:
#!        operator:
#!        value:
#!        effect:
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - data
                      - monitor
                  - key: postgres-instance
                    operator: In
                    values:
                      - postgres-sample
              topologyKey: kubernetes.io/hostname
            weight: 100


 #!
 #! Monitor Pod features
 #!
  monitorStorageClassName: #@data.values.storage_class_name
  monitorStorageSize: 1G
  monitorPodConfig:
#!    tolerations:
#!      - key:
#!        operator:
#!        value:
#!        effect:
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - data
                      - monitor
                  - key: postgres-instance
                    operator: In
                    values:
                      - postgres-sample
              topologyKey: kubernetes.io/hostname
            weight: 100

 #!
 #! Resources
 #!
  resources:
    monitor:
      limits:
        cpu: 800m
        memory: 800Mi
      requests:
        cpu: 800m
        memory: 800Mi
    metrics:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 100Mi